homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('',views.index, name='index'),
    path('profile/',views.profile, name='profile'),
    path('form/',views.form,name='form'),
    path('addMataKuliah/',views.addMataKuliah,name='addMataKuliah'),
    path('listMatkul/',views.listMatkul,name='listMatkul'),
    
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class MataKuliah(models.Model):
    nama = models.CharField(max_length=50,default='')
    dosen = models.CharField(max_length=50,default='')
    tahunAjaran = models.CharField(max_length=50,default='')
    jumlahSKS = models.CharField(max_length=50,default='')
    ruangKelas = models.CharField(max_length=50,default='')
    deskripsi = models.TextField(default='')
        


    

homepage/forms.py
from django import forms

homepage/views.py
from django.shortcuts import render
from .models import MataKuliah

# Create your views here.
def index(request):
    return render(request,'index.html')

def profile(request):
    return render(request,'profile.html')

def form(request):
    return render(request,'forms.html')

def addMataKuliah(request):
    nama = request.POST['namaMatkul']
    dosen = request.POST['dosenPengajar']
    tahunAjaran = request.POST['tahunAjaran']
    jumlahSKS = request.POST['jumlahSKS']
    ruangKelas = request.POST['ruangKelas']
    deskripsi = request.POST['deskripsi']
    info_matakuliah = MataKuliah(nama=nama,dosen=dosen,tahunAjaran=tahunAjaran,jumlahSKS=jumlahSKS,ruangKelas=ruangKelas,deskripsi=deskripsi)
    info_matakuliah.save()
    return render(request,'forms.html')

def listMatkul(request):
    data = MataKuliah.objects.all()
    matakuliah = {
        "info_matkul" : data
    }
    return render(request,'listMataKuliah.html',matakuliah)

homepage/templates/forms.html
{% load static %}
{% include 'header.html' %}

<title>Forms</title>

<div class="row">
    <div class="col-md-12">
        <h1 style="text-align: center;margin-top: 5%;">Daftarkan Jadwal Kalian</h1>
    </div>
</div>

<div class="container" style="margin-top: 5%;">
    <form action="/addMataKuliah/" class="was-validated" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="nama">Nama Mata Kuliah :</label>
          <input type="text" class="form-control" id="nama" placeholder="Masukkan nama matkul " name="namaMatkul" required>
          <div class="valid-feedback">Valid.</div>
          <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        
        <div class="form-group">
          <label for="dosen">Nama Dosen :</label>
          <input type="text" class="form-control" id="dosen" placeholder="Masukkan nama dosen" name="dosenPengajar" required>
          <div class="valid-feedback">Valid.</div>
          <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        <div class="form-group">
          <label for="dosen">Tahun Ajaran :</label>
          <input type="text" class="form-control" id="tahunAjaran" placeholder="Masukkan tahun ajaran dengan format (xxxx/xxxx)" name="tahunAjaran" required>
          <div class="valid-feedback">Valid.</div>
          <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        <div class="form-group">
            <label for="jumlahSKS">Jumlah SKS :</label>
            <input type="text" class="form-control" id="jumlahSKS" placeholder="Masukkan jumlah SKS" name="jumlahSKS" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        <div class="form-group">
            <label for="ruangKelas">Ruang Kelas :</label>
            <input type="text" class="form-control" id="ruangKelas" placeholder="Masukkan ruang kelas" name="ruangKelas" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1">Deskripsi mata kuliah : </label>
          <textarea class="form-control rounded-0" id="exampleFormControlTextarea1" rows="10" name="deskripsi"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>

homepage/templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'static/index.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'homepage:index' %}">Home</a>
                 </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:form' %}">Form Submission</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'homepage:listMatkul' %}">List Mata Kuliah</a>
                </li>
            </ul>
        </nav>
    </body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
{% include 'header.html' %}

<title>HomePage</title>


<div class="container">
    <div class="page-header">
        <h2>Welcome</h2>
    </div>
    <p>Welcome to my webpage i'll be talking about my profile in this website</p>
</div>

homepage/templates/listMataKuliah.html
{% load static %}
{% include 'header.html' %}

<title>List Mata Kuliah</title>

<div class="row">
    <div class="col-md-12" style="margin-top:5%;">
        <h1 style="text-align: center;">Daftar Mata Kuliah</h1>
    </div>
    
    {% for matakuliah in info_matkul %}
    <div class="col-md-6" style="margin-top: 5%">
        <h2 style="margin-left: 25%;">{{ matakuliah.nama }}</h2>
        <ul style="margin-left:25%;">
            <li>Nama dosen : {{ matakuliah.dosen }}</li>
            <li>Tahun Ajaran : {{ matakuliah.tahunAjaran }}</li>
            <li>Jumlah SKS : {{ matakuliah.jumlahSKS }}</li>
            <li>Ruang Kelas : {{ matakuliah.ruangKelas }}</li>
            <li>Deskripsi :<br>{{ matakuliah.deskripsi }}</li>
        </ul>
    </div>  
    {% endfor %}
        

homepage/templates/profile.html
{% load static %}
{% include 'header.html' %}
<title>Profile Page</title>


<div class= "container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <img src="{% static 'img/profpic.jpg' %}" style="width: 250px;height: 225px; border-radius:100%;margin-left: 200px;">
        </div>
        <div class="col-sm-12 col-md-6">
            <h1>Selamat Datang</h1>
            <p style="font-size:20px;">Saya Ahsan</p>
            <div class="inlineContent" style="margin-top: 40px;">
                <a href="https://www.instagram.com/ahsincostan/">
                    <img src="{% static 'img/instagram.jpg' %}" alt="instagram" style="width: 30px;height: 30px;border-radius: 100%;">
                </a>
                <a href="https://twitter.com/ahsannajmy">
                    <img src="{% static 'img/twitter.png' %}" alt="twitter" style="width: 30px;height: 30px;border-radius: 100%;">
                </a>
                <a href="https://www.facebook.com/ahsannajmy/">
                    <img src="{% static 'img/facebook.png' %}" alt="facebook" style="width: 30px;height: 30px;border-radius: 100%;">
                </a>
            </div>
        </div>
    </div>
</div>

<div class="container" style="margin-top: 40px;">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="content1" style="margin-left:100px">
                <h2>Profil : </h2>
                <ul style="margin-top: 20px;">
                    <li>Nama Lengkap : Ahsan Najmy Ramadhan Putra Aji</li>
                    <li>Pendidikan Sekarang : Fakultas Ilmu Komputer, Universitas Indonesia</li>
                    <li>NPM : 1906398641</li>
                    <li>Angkatan : 2019</li>
                </ul>
            </div>
        </div>
        <div class="col-sm-12 col-md-6">
            <div class="content1">
                <h2>Riwayat Pendidikan</h2>
                <ul style="margin-top: 20px;">
                    <li>SD  (2007-2013) : Al-Azhar 2 Pasar Minggu</li>
                    <li>SMP (2013-2016) : SMPN 2 Negeri Depok</li>
                    <li>SMA (2016-2019) : SMAN 26 Negeri Jakarta</li>
                </ul>
            </div>
        </div>
    </div>

</div>